### PR TITLE
add iOS 8 support

### PR DESCRIPTION
**Pull request by wangguangfeng**
add iOS version check where the Auto Layout Layout Anchor API is used.

### CODE REVIEW

**Comment by wangguangfeng** [comment]
This pull request is for iOS 8 support

**Comment by Cosmo** [comment]
@wangguangfeng, that was quick 🚀!

One thing before merging:
I've tried your fork on the iOS 8 simulator, but the 2-finger-tap gesture does not work for me.
Any ideas?

**Comment by wangguangfeng** [comment]
The two-fingers-tap gesture on the viewcontroller is blocked by the gesture on the textview. To fix the bug, i add the two-fingers-tap gesture on the textview.

**Comment by Cosmo** [comment]
Does the 3 finger tap still work?
I can't really test or verify, because I don't own an iOS 8 device anymore.
And the development target needs to be changed to iOS 8 to make it work.

Thanks!

**Comment by wangguangfeng** [comment]
I have tested, 3-finger-tap works fine.

**Comment by Cosmo** [comment]
Ok, great! Do you want to change the deployment target to iOS 8 before I make the merge?

**Comment by wangguangfeng** [comment]
OK，but I will change the deployment target to iOS 8 tomorrow.

**Comment by wangguangfeng** [comment]
I have changed the deployment target to iOS 8.

**Comment by Cosmo** [comment]
👍 Awesome, Thanks! 

This resolves #2

**Pull request merged**
